
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexico;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCSharp extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCSharp() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCSharp(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCSharp(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\004\004\001\002\000\004\002\000\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCSharp$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCSharp$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCSharp$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




        public void syntax_error(Symbol s) {
            /* report_error("ERROR sintatico"); */
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCSharp$actions {
  private final ParserCSharp parser;

  /** Constructor */
  CUP$ParserCSharp$actions(ParserCSharp parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCSharp$do_action_part00000000(
    int                        CUP$ParserCSharp$act_num,
    java_cup.runtime.lr_parser CUP$ParserCSharp$parser,
    java.util.Stack            CUP$ParserCSharp$stack,
    int                        CUP$ParserCSharp$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCSharp$result;

      /* select the action based on the action number */
      switch (CUP$ParserCSharp$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= expr EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCSharp$stack.elementAt(CUP$ParserCSharp$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCSharp$stack.elementAt(CUP$ParserCSharp$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserCSharp$stack.elementAt(CUP$ParserCSharp$top-1)).value;
		RESULT = start_val;
              CUP$ParserCSharp$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCSharp$stack.elementAt(CUP$ParserCSharp$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCSharp$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCSharp$parser.done_parsing();
          return CUP$ParserCSharp$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // expr ::= ABSTRACT 
            {
              Object RESULT =null;

              CUP$ParserCSharp$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$ParserCSharp$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCSharp$stack.peek()), RESULT);
            }
          return CUP$ParserCSharp$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCSharp$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCSharp$do_action(
    int                        CUP$ParserCSharp$act_num,
    java_cup.runtime.lr_parser CUP$ParserCSharp$parser,
    java.util.Stack            CUP$ParserCSharp$stack,
    int                        CUP$ParserCSharp$top)
    throws java.lang.Exception
    {
              return CUP$ParserCSharp$do_action_part00000000(
                               CUP$ParserCSharp$act_num,
                               CUP$ParserCSharp$parser,
                               CUP$ParserCSharp$stack,
                               CUP$ParserCSharp$top);
    }
}

}
