// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/lexico/lexico_csharp.flex


/* Isaac Aaron Tovar Zavaleta - C# */

package lexico;

import java_cup.runtime.*;
/* Aquí el resto de importaciones */


@SuppressWarnings("fallthrough")
public class ScannerCS implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\4\1\22\0\1\2\1\3\3\0\1\4\1\5"+
    "\1\0\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\12\16\1\17\1\20\1\21\1\22\1\23\34\0"+
    "\1\24\1\0\1\25\3\0\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\0\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\7\0\1\1\u01a2\0\2\1\326\0\u0100\1";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\1\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\22\1\1\24"+
    "\1\1\1\25\1\26\1\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\2\0\1\35\1\36\1\37\1\0\1\40"+
    "\7\0\1\41\11\0\1\42\1\0\1\43\1\44\32\0"+
    "\1\45\1\20\1\33\25\0\1\46\2\0\1\47\2\0"+
    "\1\50\3\0\1\51\5\0\1\52\12\0\1\53\12\0"+
    "\1\54\1\0\1\55\1\0\1\56\10\0\1\57\1\60"+
    "\7\0\1\61\2\0\1\62\1\63\1\64\20\0\1\65"+
    "\2\0\1\66\4\0\1\67\3\0\1\70\1\71\1\72"+
    "\1\73\6\0\1\74\3\0\1\75\1\76\13\0\1\77"+
    "\1\0\1\100\5\0\1\101\1\0\1\102\1\0\1\103"+
    "\2\0\1\104\5\0\1\105\2\0\1\106\4\0\1\107"+
    "\2\0\1\110\1\0\1\111\1\0\1\112\1\113\1\114"+
    "\1\115\1\116\1\117\1\120\1\121\1\122\4\0\1\123"+
    "\1\124\1\0\1\125\1\0\1\126\1\127\4\0\1\130"+
    "\1\0\1\131\1\0\1\132\1\133\1\134\1\135\1\136"+
    "\1\137\1\140\1\141\1\142\1\143";

  private static int [] zzUnpackAction() {
    int [] result = new int[324];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\62\0\144\0\226\0\310\0\62\0\62"+
    "\0\372\0\u012c\0\62\0\u015e\0\u0190\0\u01c2\0\u01f4\0\62"+
    "\0\62\0\u0226\0\u0258\0\u028a\0\62\0\62\0\u02bc\0\u02ee"+
    "\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a\0\u044c\0\u047e"+
    "\0\u04b0\0\u04e2\0\u0514\0\u0546\0\u0578\0\u05aa\0\u05dc\0\u060e"+
    "\0\62\0\u0640\0\62\0\62\0\u0672\0\62\0\62\0\62"+
    "\0\62\0\u06a4\0\62\0\u0190\0\u01f4\0\62\0\62\0\62"+
    "\0\u06d6\0\62\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802"+
    "\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992"+
    "\0\u09c4\0\u09f6\0\u0a28\0\62\0\u0a5a\0\u0a8c\0\62\0\u0abe"+
    "\0\u0af0\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e"+
    "\0\u0c80\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde"+
    "\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a\0\u0f3c\0\u0f6e"+
    "\0\u0fa0\0\62\0\62\0\62\0\u0fd2\0\u1004\0\u1036\0\u1068"+
    "\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6\0\u11f8"+
    "\0\u122a\0\u125c\0\u128e\0\u12c0\0\u12f2\0\u1324\0\u1356\0\u1388"+
    "\0\u13ba\0\u13ec\0\u141e\0\u1450\0\u1482\0\u14b4\0\u14e6\0\62"+
    "\0\u1518\0\u154a\0\u157c\0\62\0\u15ae\0\u15e0\0\u1612\0\u1644"+
    "\0\u1676\0\62\0\u16a8\0\u16da\0\u170c\0\u173e\0\u1770\0\u17a2"+
    "\0\u17d4\0\u1806\0\u1838\0\u186a\0\62\0\u189c\0\u18ce\0\u1900"+
    "\0\u1932\0\u1964\0\u1996\0\u19c8\0\u19fa\0\u1a2c\0\u1a5e\0\62"+
    "\0\u1a90\0\62\0\u1ac2\0\62\0\u1af4\0\u1b26\0\u1b58\0\u1b8a"+
    "\0\u1bbc\0\u1bee\0\u1c20\0\u1c52\0\62\0\62\0\u1c84\0\u1cb6"+
    "\0\u1ce8\0\u1d1a\0\u1d4c\0\u1d7e\0\u1db0\0\62\0\u1de2\0\u1e14"+
    "\0\62\0\62\0\62\0\u1e46\0\u1e78\0\u1eaa\0\u1edc\0\u1f0e"+
    "\0\u1f40\0\u1f72\0\u1fa4\0\u1fd6\0\u2008\0\u203a\0\u206c\0\u209e"+
    "\0\u20d0\0\u2102\0\u2134\0\62\0\u2166\0\u2198\0\62\0\u21ca"+
    "\0\u21fc\0\u222e\0\u2260\0\62\0\u2292\0\u22c4\0\u22f6\0\62"+
    "\0\62\0\62\0\62\0\u2328\0\u235a\0\u238c\0\u23be\0\u23f0"+
    "\0\u2422\0\62\0\u2454\0\u2486\0\u24b8\0\62\0\62\0\u24ea"+
    "\0\u251c\0\u254e\0\u2580\0\u25b2\0\u25e4\0\u2616\0\u2648\0\u267a"+
    "\0\u26ac\0\u26de\0\62\0\u2710\0\62\0\u2742\0\u2774\0\u27a6"+
    "\0\u27d8\0\u280a\0\62\0\u283c\0\62\0\u286e\0\62\0\u28a0"+
    "\0\u28d2\0\62\0\u2904\0\u2936\0\u2968\0\u299a\0\u29cc\0\62"+
    "\0\u29fe\0\u2a30\0\62\0\u2a62\0\u2a94\0\u2ac6\0\u2af8\0\62"+
    "\0\u2b2a\0\u2b5c\0\62\0\u2b8e\0\62\0\u2bc0\0\62\0\62"+
    "\0\62\0\62\0\62\0\62\0\62\0\62\0\62\0\u2bf2"+
    "\0\u2c24\0\u2c56\0\u2c88\0\62\0\62\0\u2cba\0\62\0\u2cec"+
    "\0\62\0\62\0\u2d1e\0\u2d50\0\u2d82\0\u2db4\0\62\0\u2de6"+
    "\0\62\0\u2e18\0\62\0\62\0\62\0\62\0\62\0\62"+
    "\0\62\0\62\0\62\0\62";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[324];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\0\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\2\1\36\2\2"+
    "\1\37\1\2\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\3\2\1\51\1\52\1\53\104\0"+
    "\1\54\43\0\1\55\62\0\1\56\76\0\1\57\61\0"+
    "\1\60\61\0\1\61\55\0\1\62\65\0\1\63\53\0"+
    "\1\64\1\0\1\65\65\0\1\66\61\0\1\67\61\0"+
    "\1\70\66\0\1\71\17\0\1\72\56\0\1\73\1\0"+
    "\1\74\41\0\1\75\6\0\1\76\3\0\1\77\2\0"+
    "\1\100\47\0\1\101\11\0\1\102\10\0\1\103\45\0"+
    "\1\104\1\0\1\105\6\0\1\106\1\0\1\107\43\0"+
    "\1\110\2\0\1\111\2\0\1\112\61\0\1\113\50\0"+
    "\1\114\6\0\1\115\1\116\3\0\1\117\56\0\1\120"+
    "\47\0\1\121\16\0\1\122\37\0\1\123\15\0\1\124"+
    "\3\0\1\125\1\126\35\0\1\127\17\0\1\130\2\0"+
    "\1\131\42\0\1\132\56\0\1\133\2\0\1\134\2\0"+
    "\1\135\1\136\11\0\1\137\2\0\1\140\43\0\1\141"+
    "\10\0\1\142\6\0\1\143\42\0\1\144\2\0\1\145"+
    "\5\0\1\146\50\0\1\147\5\0\1\150\52\0\1\151"+
    "\104\0\1\152\23\0\1\153\55\0\1\154\112\0\1\155"+
    "\56\0\1\156\47\0\1\157\76\0\1\160\1\161\37\0"+
    "\1\162\61\0\1\163\76\0\1\164\46\0\1\165\2\0"+
    "\1\166\5\0\1\167\71\0\1\170\53\0\1\171\65\0"+
    "\1\172\63\0\1\173\42\0\1\174\74\0\1\175\2\0"+
    "\1\176\54\0\1\177\10\0\1\200\51\0\1\201\63\0"+
    "\1\202\63\0\1\203\56\0\1\204\64\0\1\205\41\0"+
    "\1\206\12\0\1\207\71\0\1\210\47\0\1\211\57\0"+
    "\1\212\54\0\1\213\77\0\1\214\43\0\1\215\75\0"+
    "\1\216\51\0\1\217\52\0\1\220\60\0\1\221\4\0"+
    "\1\222\14\0\1\223\66\0\1\224\32\0\1\225\77\0"+
    "\1\226\73\0\1\227\31\0\1\230\17\0\1\231\51\0"+
    "\1\232\61\0\1\233\7\0\1\234\70\0\1\235\51\0"+
    "\1\236\57\0\1\237\62\0\1\240\52\0\1\241\1\242"+
    "\71\0\1\243\51\0\1\244\2\0\1\245\56\0\1\246"+
    "\73\0\1\247\52\0\1\250\46\0\1\251\65\0\1\252"+
    "\57\0\1\253\77\0\1\254\62\0\1\255\61\0\1\256"+
    "\1\257\47\0\1\260\51\0\1\261\65\0\1\262\56\0"+
    "\1\263\60\0\1\264\65\0\1\265\71\0\1\266\62\0"+
    "\1\267\57\0\1\270\52\0\1\271\55\0\1\272\65\0"+
    "\1\273\55\0\1\274\65\0\1\275\73\0\1\276\56\0"+
    "\1\277\52\0\1\300\67\0\1\301\55\0\1\302\66\0"+
    "\1\303\52\0\1\304\75\0\1\305\61\0\1\306\41\0"+
    "\1\307\105\0\1\310\50\0\1\311\51\0\1\312\101\0"+
    "\1\313\60\0\1\314\52\0\1\315\66\0\1\316\45\0"+
    "\1\317\77\0\1\320\47\0\1\321\12\0\1\322\60\0"+
    "\1\323\60\0\1\324\56\0\1\325\47\0\1\326\77\0"+
    "\1\327\54\0\1\330\62\0\1\331\60\0\1\332\66\0"+
    "\1\333\42\0\1\334\56\0\1\335\74\0\1\336\66\0"+
    "\1\337\53\0\1\340\56\0\1\341\73\0\1\342\62\0"+
    "\1\343\47\0\1\344\65\0\1\345\70\0\1\346\44\0"+
    "\1\347\66\0\1\350\62\0\1\351\67\0\1\352\47\0"+
    "\1\353\71\0\1\354\54\0\1\355\51\0\1\356\100\0"+
    "\1\357\37\0\1\360\71\0\1\361\71\0\1\362\43\0"+
    "\1\363\57\0\1\364\101\0\1\365\55\0\1\366\45\0"+
    "\1\367\71\0\1\370\67\0\1\371\63\0\1\372\45\0"+
    "\1\373\61\0\1\374\77\0\1\375\55\0\1\376\53\0"+
    "\1\377\66\0\1\u0100\46\0\1\u0101\61\0\1\u0102\104\0"+
    "\1\u0103\52\0\1\u0104\51\0\1\u0105\73\0\1\u0106\47\0"+
    "\1\u0107\76\0\1\u0108\60\0\1\u0109\43\0\1\u010a\55\0"+
    "\1\u010b\76\0\1\u010c\44\0\1\u010d\74\0\1\u010e\46\0"+
    "\1\u010f\65\0\1\u0110\65\0\1\u0111\53\0\1\u0112\74\0"+
    "\1\u0113\57\0\1\u0114\50\0\1\u0115\61\0\1\u0116\74\0"+
    "\1\u0117\66\0\1\u0118\61\0\1\u0119\47\0\1\u011a\72\0"+
    "\1\u011b\62\0\1\u011c\41\0\1\u011d\74\0\1\u011e\61\0"+
    "\1\u011f\47\0\1\u0120\63\0\1\u0121\56\0\1\u0122\65\0"+
    "\1\u0123\75\0\1\u0124\46\0\1\u0125\57\0\1\u0126\76\0"+
    "\1\u0127\37\0\1\u0128\71\0\1\u0129\53\0\1\u012a\102\0"+
    "\1\u012b\51\0\1\u012c\70\0\1\u012d\61\0\1\u012e\41\0"+
    "\1\u012f\67\0\1\u0130\100\0\1\u0131\41\0\1\u0132\62\0"+
    "\1\u0133\51\0\1\u0134\77\0\1\u0135\46\0\1\u0136\62\0"+
    "\1\u0137\70\0\1\u0138\61\0\1\u0139\61\0\1\u013a\70\0"+
    "\1\u013b\43\0\1\u013c\61\0\1\u013d\77\0\1\u013e\61\0"+
    "\1\u013f\52\0\1\u0140\66\0\1\u0141\45\0\1\u0142\104\0"+
    "\1\u0143\36\0\1\u0144\27\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[11850];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\2\11\2\1\1\11\4\1\2\11"+
    "\3\1\2\11\22\1\1\11\1\1\2\11\1\0\4\11"+
    "\1\1\1\11\2\0\3\11\1\0\1\11\7\0\1\1"+
    "\11\0\1\11\1\0\1\1\1\11\32\0\3\11\25\0"+
    "\1\1\2\0\1\1\2\0\1\11\3\0\1\11\5\0"+
    "\1\11\12\0\1\11\12\0\1\11\1\0\1\11\1\0"+
    "\1\11\10\0\2\11\7\0\1\11\2\0\3\11\20\0"+
    "\1\11\2\0\1\11\4\0\1\11\3\0\4\11\6\0"+
    "\1\11\3\0\2\11\13\0\1\11\1\0\1\11\5\0"+
    "\1\11\1\0\1\11\1\0\1\11\2\0\1\11\5\0"+
    "\1\11\2\0\1\11\4\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\11\11\4\0\2\11\1\0\1\11\1\0"+
    "\2\11\4\0\1\11\1\0\1\11\1\0\12\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[324];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  StringBuilder string = new StringBuilder();
  
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScannerCS(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("ERROR Esto no es un token del lenguaje "+yytext());
            }
          // fall through
          case 100: break;
          case 2:
            { System.out.println("Espacio"); return symbol(sym.ESPACIO, yytext());
            }
          // fall through
          case 101: break;
          case 3:
            { System.out.println("Signo not"); return symbol(sym.NOT, yytext());
            }
          // fall through
          case 102: break;
          case 4:
            { System.out.println("Signo modulo"); return symbol(sym.MOD, yytext());
            }
          // fall through
          case 103: break;
          case 5:
            { System.out.println("Signo parentesis de apertura"); return symbol(sym.LPAREN, yytext());
            }
          // fall through
          case 104: break;
          case 6:
            { System.out.println("Signo parentesis de cierre"); return symbol(sym.RPAREN, yytext());
            }
          // fall through
          case 105: break;
          case 7:
            { System.out.println("Signo multiplicacion"); return symbol(sym.MULT, yytext());
            }
          // fall through
          case 106: break;
          case 8:
            { System.out.println("Signo mas"); return symbol(sym.PLUS, yytext());
            }
          // fall through
          case 107: break;
          case 9:
            { System.out.println("Signo coma"); return symbol(sym.COMMA, yytext());
            }
          // fall through
          case 108: break;
          case 10:
            { System.out.println("Signo menos"); return symbol(sym.MINUS, yytext());
            }
          // fall through
          case 109: break;
          case 11:
            { System.out.println("Signo punto"); return symbol(sym.DOT, yytext());
            }
          // fall through
          case 110: break;
          case 12:
            { System.out.println("Signo division"); return symbol(sym.DIV, yytext());
            }
          // fall through
          case 111: break;
          case 13:
            { System.out.println("Signo dos puntos"); return symbol(sym.COLON, yytext());
            }
          // fall through
          case 112: break;
          case 14:
            { System.out.println("Signo punto y coma"); return symbol(sym.SEMICOLON, yytext());
            }
          // fall through
          case 113: break;
          case 15:
            { System.out.println("Signo menor que"); return symbol(sym.LT, yytext());
            }
          // fall through
          case 114: break;
          case 16:
            { System.out.println("Signo igual"); return symbol(sym.ASSING, yytext());
            }
          // fall through
          case 115: break;
          case 17:
            { System.out.println("Signo mayor que"); return symbol(sym.GT, yytext());
            }
          // fall through
          case 116: break;
          case 18:
            { System.out.println("Signo corchete de apertura"); return symbol(sym.LBRACKET, yytext());
            }
          // fall through
          case 117: break;
          case 19:
            { System.out.println("Signo corchete de cierre"); return symbol(sym.RBRACKET, yytext());
            }
          // fall through
          case 118: break;
          case 20:
            { System.out.println("Signo llave de apertura"); return symbol(sym.LBRACE, yytext());
            }
          // fall through
          case 119: break;
          case 21:
            { System.out.println("Signo llave de cierre"); return symbol(sym.RBRACE, yytext());
            }
          // fall through
          case 120: break;
          case 22:
            { System.out.println("Signo diferente de"); return symbol(sym.NEQ, yytext());
            }
          // fall through
          case 121: break;
          case 23:
            { System.out.println("Signo and"); return symbol(sym.AND, yytext());
            }
          // fall through
          case 122: break;
          case 24:
            { System.out.println("Signo multiplicacion igual"); return symbol(sym.MULT_ASSIGN, yytext());
            }
          // fall through
          case 123: break;
          case 25:
            { System.out.println("Signo mas igual"); return symbol(sym.PLUS_ASSIGN, yytext());
            }
          // fall through
          case 124: break;
          case 26:
            { System.out.println("Signo menos igual"); return symbol(sym.MINUS_ASSIGN, yytext());
            }
          // fall through
          case 125: break;
          case 27:
            { System.out.println("Numero decimal"); return symbol(sym.NDECIMAL, yytext());
            }
          // fall through
          case 126: break;
          case 28:
            { System.out.println("Signo division igual"); return symbol(sym.DIV_ASSIGN, yytext());
            }
          // fall through
          case 127: break;
          case 29:
            { System.out.println("Signo menor o igual que"); return symbol(sym.LTE, yytext());
            }
          // fall through
          case 128: break;
          case 30:
            { System.out.println("Signo igual igual"); return symbol(sym.EQ, yytext());
            }
          // fall through
          case 129: break;
          case 31:
            { System.out.println("Signo mayor o igual que"); return symbol(sym.GTE, yytext());
            }
          // fall through
          case 130: break;
          case 32:
            { System.out.println("Es una palabra clave de conversion"); return symbol(sym.AS, yytext());
            }
          // fall through
          case 131: break;
          case 33:
            { System.out.println("Es una instruccion de bucle do-while"); return symbol(sym.DO, yytext());
            }
          // fall through
          case 132: break;
          case 34:
            { System.out.println("Es una estructura de control de flujo"); return symbol(sym.IF, yytext());
            }
          // fall through
          case 133: break;
          case 35:
            { System.out.println("Es una palabra clave utilizada en expresiones de consulta LINQ"); return symbol(sym.IN, yytext());
            }
          // fall through
          case 134: break;
          case 36:
            { System.out.println("Es una palabra clave para verificar el tipo"); return symbol(sym.IS, yytext());
            }
          // fall through
          case 135: break;
          case 37:
            { System.out.println("Signo or"); return symbol(sym.OR, yytext());
            }
          // fall through
          case 136: break;
          case 38:
            { System.out.println("Es una instruccion de bucle for"); return symbol(sym.FOR, yytext());
            }
          // fall through
          case 137: break;
          case 39:
            { System.out.println("Es un tipo de dato entero"); return symbol(sym.INT, yytext());
            }
          // fall through
          case 138: break;
          case 40:
            { System.out.println("Es una palabra clave para crear nuevas instancias"); return symbol(sym.NEW, yytext());
            }
          // fall through
          case 139: break;
          case 41:
            { System.out.println("Es una palabra clave para redireccionar la salida"); return symbol(sym.OUT, yytext());
            }
          // fall through
          case 140: break;
          case 42:
            { System.out.println("Es una palabra clave para pasar parametros por referencia"); return symbol(sym.REF, yytext());
            }
          // fall through
          case 141: break;
          case 43:
            { System.out.println("Es una clausula para intentar ejecutar código con manejo de excepciones"); return symbol(sym.TRY, yytext());
            }
          // fall through
          case 142: break;
          case 44:
            { System.out.println("Es un tipo de dato booleano"); return symbol(sym.BOOL, yytext());
            }
          // fall through
          case 143: break;
          case 45:
            { System.out.println("Es una etiqueta en una instruccion switch"); return symbol(sym.CASE, yytext());
            }
          // fall through
          case 144: break;
          case 46:
            { System.out.println("Es un tipo de dato caracter"); return symbol(sym.CHAR, yytext());
            }
          // fall through
          case 145: break;
          case 47:
            { System.out.println("Es una instruccion alternativa en una estructura if"); return symbol(sym.ELSE, yytext());
            }
          // fall through
          case 146: break;
          case 48:
            { System.out.println("Es una definicion de un tipo enumerado"); return symbol(sym.ENUM, yytext());
            }
          // fall through
          case 147: break;
          case 49:
            { System.out.println("Es una instruccion para saltar a una etiqueta"); return symbol(sym.GOTO, yytext());
            }
          // fall through
          case 148: break;
          case 50:
            { System.out.println("Es una palabra clave para sincronización de hilos"); return symbol(sym.LOCK, yytext());
            }
          // fall through
          case 149: break;
          case 51:
            { System.out.println("Es un tipo de dato entero de 64 bits"); return symbol(sym.LONG, yytext());
            }
          // fall through
          case 150: break;
          case 52:
            { System.out.println("Es un valor nulo"); return symbol(sym.NULL, yytext());
            }
          // fall through
          case 151: break;
          case 53:
            { System.out.println("Es una referencia a la instancia actual de la clase"); return symbol(sym.THIS, yytext());
            }
          // fall through
          case 152: break;
          case 54:
            { System.out.println("Es un tipo de dato entero sin signo de 32 bits"); return symbol(sym.UINT, yytext());
            }
          // fall through
          case 153: break;
          case 55:
            { System.out.println("Es un tipo de dato vacio"); return symbol(sym.VOID, yytext());
            }
          // fall through
          case 154: break;
          case 56:
            { System.out.println("Es una instruccion para salir de un bucle"); return symbol(sym.BREAK, yytext());
            }
          // fall through
          case 155: break;
          case 57:
            { System.out.println("Es una clausula para capturar excepciones"); return symbol(sym.CATCH, yytext());
            }
          // fall through
          case 156: break;
          case 58:
            { System.out.println("Es una definicion de una clase"); return symbol(sym.CLASS, yytext());
            }
          // fall through
          case 157: break;
          case 59:
            { System.out.println("Es una constante de valor fijo"); return symbol(sym.CONST, yytext());
            }
          // fall through
          case 158: break;
          case 60:
            { System.out.println("Es un tipo de dato que representa un evento"); return symbol(sym.EVENT, yytext());
            }
          // fall through
          case 159: break;
          case 61:
            { System.out.println("Es una palabra clave para trabajar con memoria fija"); return symbol(sym.FIXED, yytext());
            }
          // fall through
          case 160: break;
          case 62:
            { System.out.println("Es un tipo de dato de punto flotante"); return symbol(sym.FLOAT, yytext());
            }
          // fall through
          case 161: break;
          case 63:
            { System.out.println("Es un tipo de dato entero con signo de 8 bits"); return symbol(sym.SBYTE, yytext());
            }
          // fall through
          case 162: break;
          case 64:
            { System.out.println("Es un tipo de dato entero de 16 bits"); return symbol(sym.SHORT, yytext());
            }
          // fall through
          case 163: break;
          case 65:
            { System.out.println("Es una instrucción para lanzar una excepción"); return symbol(sym.THROW, yytext());
            }
          // fall through
          case 164: break;
          case 66:
            { System.out.println("Es un tipo de dato entero sin signo de 64 bits"); return symbol(sym.ULONG, yytext());
            }
          // fall through
          case 165: break;
          case 67:
            { System.out.println("Es una palabra clave para importar espacios de nombres"); return symbol(sym.USING, yytext());
            }
          // fall through
          case 166: break;
          case 68:
            { System.out.println("Es un bucle de repeticion"); return symbol(sym.WHILE, yytext());
            }
          // fall through
          case 167: break;
          case 69:
            { System.out.println("Es un tipo de dato de punto flotante de doble precision"); return symbol(sym.DOUBLE, yytext());
            }
          // fall through
          case 168: break;
          case 70:
            { System.out.println("Es una declaracion de metodo externo"); return symbol(sym.EXTERN, yytext());
            }
          // fall through
          case 169: break;
          case 71:
            { System.out.println("Es el tipo base de todos los tipos"); return symbol(sym.OBJECT, yytext());
            }
          // fall through
          case 170: break;
          case 72:
            { System.out.println("Es una palabra clave para parametros variables"); return symbol(sym.PARAMS, yytext());
            }
          // fall through
          case 171: break;
          case 73:
            { System.out.println("Es un modificador de acceso publico"); return symbol(sym.PUBLIC, yytext());
            }
          // fall through
          case 172: break;
          case 74:
            { System.out.println("Es una declaracion para devolver un valor"); return symbol(sym.RETURN, yytext());
            }
          // fall through
          case 173: break;
          case 75:
            { System.out.println("Es un modificador que indica que una clase no puede ser heredada"); return symbol(sym.SEALED, yytext());
            }
          // fall through
          case 174: break;
          case 76:
            { System.out.println("Es una operación que devuelve la medida de un tipo"); return symbol(sym.SIZEOF, yytext());
            }
          // fall through
          case 175: break;
          case 77:
            { System.out.println("Es un modificador que indica que el miembro pertenece a la clase"); return symbol(sym.STATIC, yytext());
            }
          // fall through
          case 176: break;
          case 78:
            { System.out.println("Es un tipo de dato cadena de caracteres"); return symbol(sym.STRING, yytext());
            }
          // fall through
          case 177: break;
          case 79:
            { System.out.println("Es una definición de una estructura"); return symbol(sym.STRUCT, yytext());
            }
          // fall through
          case 178: break;
          case 80:
            { System.out.println("Es una estructura de control de flujo de multiples opciones"); return symbol(sym.SWITCH, yytext());
            }
          // fall through
          case 179: break;
          case 81:
            { System.out.println("Es una operación que devuelve el tipo de un objeto"); return symbol(sym.TYPEOF, yytext());
            }
          // fall through
          case 180: break;
          case 82:
            { System.out.println("Es un tipo de dato entero sin signo de 16 bits"); return symbol(sym.USHORT, yytext());
            }
          // fall through
          case 181: break;
          case 83:
            { System.out.println("Es un tipo de dato decimal"); return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 182: break;
          case 84:
            { System.out.println("Es una etiqueta por defecto en una instruccion switch"); return symbol(sym.DEFAULT, yytext());
            }
          // fall through
          case 183: break;
          case 85:
            { System.out.println("Es un tipo de dato dinamico"); return symbol(sym.DYNAMIC, yytext());
            }
          // fall through
          case 184: break;
          case 86:
            { System.out.println("Es una clausula que se ejecuta despues de una excepcion"); return symbol(sym.FINALLY, yytext());
            }
          // fall through
          case 185: break;
          case 87:
            { System.out.println("Es una instruccion de bucle foreach"); return symbol(sym.FOREACH, yytext());
            }
          // fall through
          case 186: break;
          case 88:
            { System.out.println("Es un modificador de acceso privado"); return symbol(sym.PRIVATE, yytext());
            }
          // fall through
          case 187: break;
          case 89:
            { System.out.println("Es un modificador que permite que un método sea sobrescrito"); return symbol(sym.VIRTUAL, yytext());
            }
          // fall through
          case 188: break;
          case 90:
            { System.out.println("Es una palabra clave abstracta"); return symbol(sym.ABSTRACT, yytext());
            }
          // fall through
          case 189: break;
          case 91:
            { System.out.println("Es una instruccion para continuar con la siguiente iteracion"); return symbol(sym.CONTINUE, yytext());
            }
          // fall through
          case 190: break;
          case 92:
            { System.out.println("Es un tipo de dato que representa un metodo"); return symbol(sym.DELEGATE, yytext());
            }
          // fall through
          case 191: break;
          case 93:
            { System.out.println("Es una conversion explicita de tipos"); return symbol(sym.EXPLICIT, yytext());
            }
          // fall through
          case 192: break;
          case 94:
            { System.out.println("Es una conversion implicita de tipos"); return symbol(sym.IMPLICIT, yytext());
            }
          // fall through
          case 193: break;
          case 95:
            { System.out.println("Es un modificador de acceso interno"); return symbol(sym.INTERNAL, yytext());
            }
          // fall through
          case 194: break;
          case 96:
            { System.out.println("Es una definicion de operador"); return symbol(sym.OPERATOR, yytext());
            }
          // fall through
          case 195: break;
          case 97:
            { System.out.println("Es una palabra clave para sobrescribir metodos"); return symbol(sym.OVERRIDE, yytext());
            }
          // fall through
          case 196: break;
          case 98:
            { System.out.println("Es un modificador que indica que el valor es de solo lectura"); return symbol(sym.READONLY, yytext());
            }
          // fall through
          case 197: break;
          case 99:
            { System.out.println("Es un modificador que indica que el valor puede ser cambiado por otros hilos"); return symbol(sym.VOLATILE, yytext());
            }
          // fall through
          case 198: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
