
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 55;
  public static final int AS = 3;
  public static final int INTERNAL = 35;
  public static final int BOOL = 4;
  public static final int TYPEOF = 65;
  public static final int CONST = 11;
  public static final int DYNAMIC = 18;
  public static final int DELEGATE = 15;
  public static final int NAMESPACE = 39;
  public static final int ENUM = 20;
  public static final int SIZEOF = 56;
  public static final int READONLY = 50;
  public static final int CATCH = 8;
  public static final int EXPLICIT = 22;
  public static final int VIRTUAL = 70;
  public static final int THROW = 63;
  public static final int LOCK = 37;
  public static final int USHORT = 68;
  public static final int DOUBLE = 17;
  public static final int STRUCT = 60;
  public static final int PROTECTED = 48;
  public static final int OUT = 44;
  public static final int SBYTE = 53;
  public static final int OBJECT = 42;
  public static final int OVERRIDE = 45;
  public static final int FLOAT = 26;
  public static final int GOTO = 29;
  public static final int PARAMS = 46;
  public static final int FIXED = 25;
  public static final int CLASS = 10;
  public static final int ABSTRACT = 2;
  public static final int ULONG = 67;
  public static final int LONG = 38;
  public static final int WHILE = 73;
  public static final int STACKALLOC = 57;
  public static final int DECIMAL = 13;
  public static final int INTERFACE = 34;
  public static final int CHAR = 9;
  public static final int SWITCH = 61;
  public static final int DO = 16;
  public static final int FOR = 27;
  public static final int VOID = 71;
  public static final int EXTERN = 23;
  public static final int PUBLIC = 49;
  public static final int RETURN = 52;
  public static final int ELSE = 19;
  public static final int TRY = 64;
  public static final int BREAK = 5;
  public static final int INT = 33;
  public static final int NULL = 41;
  public static final int EOF = 0;
  public static final int THIS = 62;
  public static final int DEFAULT = 14;
  public static final int SEALED = 54;
  public static final int OPERATOR = 43;
  public static final int IS = 36;
  public static final int IN = 32;
  public static final int error = 1;
  public static final int FINALLY = 24;
  public static final int CONTINUE = 12;
  public static final int IF = 30;
  public static final int USING = 69;
  public static final int UINT = 66;
  public static final int FOREACH = 28;
  public static final int REF = 51;
  public static final int VOLATILE = 72;
  public static final int CASE = 7;
  public static final int NEW = 40;
  public static final int STRING = 59;
  public static final int ESPACIO = 74;
  public static final int BYTE = 6;
  public static final int PRIVATE = 47;
  public static final int STATIC = 58;
  public static final int IMPLICIT = 31;
  public static final int EVENT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABSTRACT",
  "AS",
  "BOOL",
  "BREAK",
  "BYTE",
  "CASE",
  "CATCH",
  "CHAR",
  "CLASS",
  "CONST",
  "CONTINUE",
  "DECIMAL",
  "DEFAULT",
  "DELEGATE",
  "DO",
  "DOUBLE",
  "DYNAMIC",
  "ELSE",
  "ENUM",
  "EVENT",
  "EXPLICIT",
  "EXTERN",
  "FINALLY",
  "FIXED",
  "FLOAT",
  "FOR",
  "FOREACH",
  "GOTO",
  "IF",
  "IMPLICIT",
  "IN",
  "INT",
  "INTERFACE",
  "INTERNAL",
  "IS",
  "LOCK",
  "LONG",
  "NAMESPACE",
  "NEW",
  "NULL",
  "OBJECT",
  "OPERATOR",
  "OUT",
  "OVERRIDE",
  "PARAMS",
  "PRIVATE",
  "PROTECTED",
  "PUBLIC",
  "READONLY",
  "REF",
  "RETURN",
  "SBYTE",
  "SEALED",
  "SHORT",
  "SIZEOF",
  "STACKALLOC",
  "STATIC",
  "STRING",
  "STRUCT",
  "SWITCH",
  "THIS",
  "THROW",
  "TRY",
  "TYPEOF",
  "UINT",
  "ULONG",
  "USHORT",
  "USING",
  "VIRTUAL",
  "VOID",
  "VOLATILE",
  "WHILE",
  "ESPACIO"
  };
}

