
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 12 22:12:01 CST 2024
//----------------------------------------------------

package demo_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 9;
  public static final int INT = 2;
  public static final int LONG = 3;
  public static final int PUNTO_COMA = 10;
  public static final int ENTERO = 12;
  public static final int BOOLEAN = 7;
  public static final int EOF = 0;
  public static final int DOUBLE = 6;
  public static final int ID = 11;
  public static final int ASIGNACION = 8;
  public static final int error = 1;
  public static final int BYTE = 4;
  public static final int CHAR = 5;
  public static final int FLOAT = 13;
}

