
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act5;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_DERECHO = 35;
  public static final int O_LOGICO = 52;
  public static final int LLAVE_DERECHA = 37;
  public static final int PARENTESIS_IZQUIERDO = 34;
  public static final int CONST = 28;
  public static final int CHAR = 15;
  public static final int NAMESPACE = 4;
  public static final int USING = 3;
  public static final int CASE = 24;
  public static final int RESTA = 41;
  public static final int DOS_PUNTOS = 56;
  public static final int PRIVATE = 7;
  public static final int INT = 11;
  public static final int FOR = 20;
  public static final int CORCHETE_DERECHO = 39;
  public static final int STATIC = 26;
  public static final int CONSTANTE = 63;
  public static final int IDENTIFICADOR = 65;
  public static final int CWLINE = 60;
  public static final int CARACTER = 58;
  public static final int IGUALDAD = 45;
  public static final int NENTERO = 62;
  public static final int BOOL = 13;
  public static final int CLASS = 5;
  public static final int INCREMENTO = 53;
  public static final int SUMA = 40;
  public static final int CORCHETE_IZQUIERDO = 38;
  public static final int MAIN = 30;
  public static final int IF = 18;
  public static final int PUNTO_COMA = 31;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int TRUE = 16;
  public static final int DECREMENTO = 55;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int CADENA = 57;
  public static final int NEGACION = 54;
  public static final int NDECIMAL = 64;
  public static final int MAYOR_QUE = 48;
  public static final int BREAK = 29;
  public static final int VOID = 10;
  public static final int ASIGNACION = 44;
  public static final int SWITCH = 23;
  public static final int CRLINE = 61;
  public static final int ELSE = 19;
  public static final int PROTECTED = 8;
  public static final int PUNTO = 32;
  public static final int DESIGUALDAD = 46;
  public static final int PACKAGE = 2;
  public static final int WHILE = 21;
  public static final int DEFAULT = 25;
  public static final int Y_LOGICO = 51;
  public static final int FLOAT = 14;
  public static final int PUBLIC = 6;
  public static final int CWRITE = 59;
  public static final int MAYOR_O_IGUAL_QUE = 50;
  public static final int LLAVE_IZQUIERDA = 36;
  public static final int STRING = 12;
  public static final int MENOR_QUE = 47;
  public static final int FALSE = 17;
  public static final int DIVISION = 43;
  public static final int MULTIPLICACION = 42;
  public static final int INTERNAL = 9;
  public static final int MENOR_O_IGUAL_QUE = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "USING",
  "NAMESPACE",
  "CLASS",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "INTERNAL",
  "VOID",
  "INT",
  "STRING",
  "BOOL",
  "FLOAT",
  "CHAR",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "RETURN",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "STATIC",
  "NEW",
  "CONST",
  "BREAK",
  "MAIN",
  "PUNTO_COMA",
  "PUNTO",
  "COMA",
  "PARENTESIS_IZQUIERDO",
  "PARENTESIS_DERECHO",
  "LLAVE_IZQUIERDA",
  "LLAVE_DERECHA",
  "CORCHETE_IZQUIERDO",
  "CORCHETE_DERECHO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "ASIGNACION",
  "IGUALDAD",
  "DESIGUALDAD",
  "MENOR_QUE",
  "MAYOR_QUE",
  "MENOR_O_IGUAL_QUE",
  "MAYOR_O_IGUAL_QUE",
  "Y_LOGICO",
  "O_LOGICO",
  "INCREMENTO",
  "NEGACION",
  "DECREMENTO",
  "DOS_PUNTOS",
  "CADENA",
  "CARACTER",
  "CWRITE",
  "CWLINE",
  "CRLINE",
  "NENTERO",
  "CONSTANTE",
  "NDECIMAL",
  "IDENTIFICADOR"
  };
}

