
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 4;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 5;
  public static final int PUNTO_COMA = 3;
  public static final int PACKAGE = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "PUNTO_COMA",
  "PUNTO",
  "IDENTIFICADOR"
  };
}

